version: '3'

services:
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - 9091:9091
    networks:
      - internal
    env_file:
      - transmission.env
      - transmission_authentication.env
      - compose.env
    volumes:
      - ${MOUNT_POINT}/transmission:/data
      - ${DOWNLOAD_FOLDER}/completed:/data/completed
      - ${DOWNLOAD_FOLDER}/incomplete:/data/incomplete
      - ${MOUNT_POINT}/${VPN_CONF_FILE}:/etc/openvpn/custom/default.ovpn
      - ${MOUNT_POINT}/${VPN_AUTH_FILE}:/etc/openvpn/custom/auth.txt

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    networks:
      - internal
    env_file:
      - compose.env
    volumes:
      - ${MOUNT_POINT}/radarr-config:/config
      - ${MOVIES_FOLDER}/:/downloads
      - ${DOWNLOAD_FOLDER}/:/data/
      # - ${MOUNT_POINT}/transmission/:/data
    depends_on:
      - transmission
      - jackett

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117
    networks:
      - internal
    env_file:
      - compose.env
    volumes:
      - ${MOUNT_POINT}/jackett/config/:/config
      - ${MOUNT_POINT}/jackett/downloads/:/downloads

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    env_file:
      - compose.env
    environment:
      - ADVERTISE_IP=http://192.168.1.100:32400/
    hostname: plex
    networks:
      - internal
    volumes:
      - ${MOUNT_POINT}/plex-config/:/config
      - ${DOWNLOAD_FOLDER}/completed:/data/completed_downloads
      - ${MOVIES_FOLDER}:/data/movies

networks:
  internal:
    driver: bridge